Kk lesson 2
AlexJavaGuru/java_1_wednesday_2022 pull request #10
Opened 2022-01-29 09:51 UTC by CO5M1C

2022-01-29 19:42 UTC, AlexJavaGuru requested changes
Чуть-чуть поправить нужно.

2022-01-29 19:42 UTC, AlexJavaGuru requested changes
Чуть-чуть поправить нужно.

2022-01-29 19:42 UTC, AlexJavaGuru requested changes
Чуть-чуть поправить нужно.

2022-01-30 08:49 UTC, CO5M1C commented on src/student_konstantin_kolesnik/lesson2/level_1/Task1.java
> +        var resultPlus = firstNumber + secondNumber;
Задания исправил. Дурная привычка, через литералы выражать переменные.  Если на практике всё по другому.... исправлюсь)

2022-02-03 19:29 UTC, AlexJavaGuru approved these changes

2022-02-03 19:29 UTC, merged