Lesson_7 homework
AlexJavaGuru/java_1_wednesday_2022 pull request #108
Opened 2022-04-12 15:11 UTC by namecolder17

В тестах CreditCard выдает неверные результаты. Не могу найти проблему

2022-05-02 20:35 UTC, AlexJavaGuru requested changes

2022-05-04 11:11 UTC, namecolder17 commented
Исправил проблему с методом withdraw. Теперь все работает как надо, но появилась проблема с кредитом. Неверное считает почему то

2022-05-17 17:22 UTC, AlexJavaGuru commented
Надо было мне в чат писать, что у вас проблемы с заданием. Сейчас как мне его принять? Если оно не работает? (((

2022-05-17 17:24 UTC, AlexJavaGuru approved these changes

2022-05-17 17:24 UTC, merged