Ni lesson 2 01
AlexJavaGuru/java_1_wednesday_2022 pull request #14
Opened 2022-01-30 13:36 UTC by nisajeva

2022-02-03 19:36 UTC, AlexJavaGuru requested changes

2022-02-03 19:36 UTC, AlexJavaGuru commented on src/studen_natalja_isajeva/lesson_2/level_1/Task1.java
> +        int div = firstNumber / secondNumber;
А если результат будет не целое число? Как выйти из ситуации не меняя типа переменной div

2022-02-05 05:33 UTC, nisajeva commented on src/studen_natalja_isajeva/lesson_2/level_1/Task1.java
> +        int div = firstNumber / secondNumber;
Не знаю, у меня никак не получается это сделать, я бы поставила 
int div = (double)firstNumber / secondNumber; - но у меня ругается и пишет , что не правильно - больше вариантов нет(

2022-02-05 05:47 UTC, nisajeva commented on src/studen_natalja_isajeva/lesson_2/level_1/Task1.java
> +        int div = firstNumber / secondNumber;
System.out.println("Divide result: " + (double)div); - тут тоже непомогло

2022-02-08 17:16 UTC, AlexJavaGuru approved these changes

2022-02-08 17:17 UTC, merged