Student igors
AlexJavaGuru/java_1_wednesday_2022 pull request #28
Opened 2022-02-03 10:18 UTC by Trigs70

2022-02-04 21:03 UTC, AlexJavaGuru requested changes
Игорь, вы сразу сделали изменения в 3 папках. У себя и еще у двух студентов. Надо исправить.

2022-02-09 07:34 UTC, Trigs70 commented
Алексей доброе утро.
Не знаю точно что надо исправить.
Как бы опять не напортить.
Игорь.
----- Reply to message -----
Subject: Re: [AlexJavaGuru/java_1_wednesday_2022] Student igors (PR #28)
Date: пт, 4 февр. 2022, 23:03
From:  AlexJavaGuru ***@***.***>
To:  AlexJavaGuru/java_1_wednesday_2022 ***@***.***>


 

@AlexJavaGuru requested changes on this pull request.

Игорь, вы сразу сделали изменения в 3 папках. У себя и еще у двух студентов. Надо исправить.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-02-10 21:58 UTC, AlexJavaGuru commented
Я Александр ) Почему вы на лекции про это ничего не сказали? Я вам сам всё поправлю.

2022-02-12 19:34 UTC, closed without merging

2022-02-12 19:44 UTC, Trigs70 commented
На последней лекции я не присутствовал