AJ_Lesson3_1
AlexJavaGuru/java_1_wednesday_2022 pull request #29
Opened 2022-02-05 13:01 UTC by JaKo2577

На 5 уровне, работал в одних и тех же классах, просто комментил лишние по ходу. 
В самом последнем задании Task33, создал дополнительный метод, для того, чтобы можно было выводить на экран скидку в %. Может был более лёгкий способ, но я не нашёл)

2022-02-08 23:43 UTC, AlexJavaGuru requested changes

2022-02-08 23:43 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/CircleDemo.java
> +        double result = circle.calculateArea(3.4);
Радиус для объекта надо передавать через конструктор.

2022-02-08 23:43 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/Computer.java
> +        this.manufacturer = manufacturer;
зачем эта строчка? Вы просто в переменную записываете то же самое значение. Её можно удалить и всё будет работать

2022-02-08 23:43 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/Computer.java
> +        this.model = model;
То же самое

2022-02-08 23:43 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/Product.java
> +    int getDiscount(double discount){
Может тут просто надо сделать setDiscount? метод, который будет меня состояние переменной discount?

2022-02-09 13:15 UTC, JaKo2577 commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/Product.java
> +    int getDiscount(double discount){
Действительно, это было проще)

2022-02-11 17:14 UTC, AlexJavaGuru requested changes

2022-02-11 17:14 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/Circle.java
> +        radius = 3.5;
в конструкторе не должно быть констант. Пусть значение приходит сюда параметром и записывается в переменную radius

2022-02-13 17:05 UTC, AlexJavaGuru requested changes

2022-02-13 17:05 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_3/level_7/Circle.java
> +    double calculateArea(double radius){
А что вы сделали? значение радиуса приходит в конструктор - было правильно. Зачем в метод calculateArea подавать радиус, если объект уже хранит свое значение? Пишите мне в личку, если не понятно. Очень долго на этом сидим. Помогу сделать

2022-02-13 17:56 UTC, AlexJavaGuru approved these changes

2022-02-13 17:56 UTC, merged