NightCatX lesson03
AlexJavaGuru/java_1_wednesday_2022 pull request #35
Opened 2022-02-06 21:56 UTC by NightCatX

lesson03

2022-02-11 16:57 UTC, AlexJavaGuru requested changes

2022-02-11 16:57 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_3/senior/Tv.java
> +    String getChannelName() {
Подправить надо ) Через switch или if else if

2022-02-11 16:57 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_3/senior/TvDemo.java
> +         else {
Ну и тут else на той же строчке, что и } скобка у if

2022-02-19 18:27 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_3/senior/Tv.java
> +    String getChannelName() {
> Подправить надо ) Через switch или if else if

done

2022-02-19 18:29 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_3/senior/TvDemo.java
> +         else {
done

2022-02-22 19:04 UTC, AlexJavaGuru approved these changes

2022-02-22 19:05 UTC, merged