Ni lesson 4 01
AlexJavaGuru/java_1_wednesday_2022 pull request #48
Opened 2022-02-13 14:12 UTC by nisajeva

2022-02-14 20:39 UTC, AlexJavaGuru requested changes

2022-02-14 20:39 UTC, AlexJavaGuru commented on src/studen_natalja_isajeva/lesson_4/level_3/Task10.java
> +        if (z>y && z>x) {
не хватает пробелов, и нормальных названий у переменных. firstNumber, secondNumber, thirdNumber - будет как раз

2022-02-14 20:39 UTC, AlexJavaGuru commented on src/studen_natalja_isajeva/lesson_4/level_3/Task8.java
> +        if ((x == y) && (x == z)) {
Исправить названия переменных

2022-02-14 20:39 UTC, AlexJavaGuru commented on src/studen_natalja_isajeva/lesson_4/level_3/Task9.java
> +        if ((x < y) && (y < z)) {
Исправить названия переменных

2022-02-15 17:43 UTC, nisajeva commented on src/studen_natalja_isajeva/lesson_4/level_3/Task10.java
> +        if (z>y && z>x) {
исправила

2022-02-19 13:54 UTC, AlexJavaGuru approved these changes

2022-02-19 13:54 UTC, merged