Ak lesson 5 01
AlexJavaGuru/java_1_wednesday_2022 pull request #60
Opened 2022-02-18 23:30 UTC by Aleksandrs2016

Aleksandr K.  - Lesson  5 (Complete Homework)

2022-02-26 09:50 UTC, AlexJavaGuru requested changes

2022-02-26 09:50 UTC, AlexJavaGuru commented on src/student_aleksandrs_korsaks/ak_lesson_5/level_2/TaskFifteen.java
> +        for (int i = 0; i < numbers.length; i++) {
Наверное надо разделить два действия. Заполнение числами и увеличение на 2

2022-02-26 09:50 UTC, AlexJavaGuru commented on src/student_aleksandrs_korsaks/ak_lesson_5/level_2/TaskFourteen.java
> +        for (int i = 0; i < numbers.length; i++) {
Разделите этот цикл на два отдельных действия. Заполнения и вычисление суммы

2022-02-27 20:16 UTC, Aleksandrs2016 commented on src/student_aleksandrs_korsaks/ak_lesson_5/level_2/TaskFourteen.java
> +        for (int i = 0; i < numbers.length; i++) {
Разве это не дублирования кода (два раза цикл, если можно одним обойтись)? Или может я не правильно понял и исправил?

2022-02-27 20:17 UTC, Aleksandrs2016 commented on src/student_aleksandrs_korsaks/ak_lesson_5/level_2/TaskFifteen.java
> +        for (int i = 0; i < numbers.length; i++) {
Разве это не дублирования кода (два раза цикл, если можно одним обойтись)? Или может я не правильно понял и исправил?

2022-03-05 07:37 UTC, AlexJavaGuru commented on src/student_aleksandrs_korsaks/ak_lesson_5/level_2/TaskFifteen.java
> +        for (int i = 0; i < numbers.length; i++) {
Нет. Цикл - это точно не дублирование. А вот два цикла, где вы делаете полностью то же самое - это дублирование

2022-03-05 07:38 UTC, AlexJavaGuru requested changes

2022-03-05 07:38 UTC, AlexJavaGuru commented on src/student_aleksandrs_korsaks/ak_lesson_5/level_2/TaskFourteen.java
> +        for (int i = 0; i < numbers.length; i++) {
Нет. Ответил выше.

2022-03-05 07:38 UTC, AlexJavaGuru commented
Все еще надо поправить

2022-03-09 19:37 UTC, AlexJavaGuru approved these changes

2022-03-09 19:37 UTC, merged