Lesson05
AlexJavaGuru/java_1_wednesday_2022 pull request #61
Opened 2022-02-19 18:04 UTC by NightCatX

lesson05

2022-02-26 09:53 UTC, AlexJavaGuru requested changes

2022-02-26 09:53 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_5/intern/Task1.java
> +        int[] numbers;
Хотелось бы чтобы массив таки создался )))

2022-02-26 09:53 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_5/middle/ArrayUtil.java
> +    int[] fillArrayWithNumbers(int length) {
Возвращать массив тут совсем не нужно. Мы это обсуждали на лекции ))

2022-03-05 07:38 UTC, AlexJavaGuru commented
Я понял, вы меня игнорируете )

2022-03-15 19:16 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_5/middle/ArrayUtil.java
> +    int[] fillArrayWithNumbers(int length) {
changed

2022-03-15 19:17 UTC, NightCatX reviewed
changed

2022-03-29 12:10 UTC, AlexJavaGuru approved these changes

2022-03-29 12:10 UTC, merged