Nadezda: lesson 3, all tasks except "class Product"
AlexJavaGuru/java_1_wednesday_2022 pull request #69
Opened 2022-02-23 09:06 UTC by Nadeezzda

2022-02-26 12:19 UTC, AlexJavaGuru requested changes

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson3/level7/Circle.java
> +class Circle {
У объекта круг должно быть состояние, которое сохраняет значение радиуса и используется в расчетах метода calculateArea

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Calculator.java
> +    public boolean isEven(int result) {
Этот метод можно упростить до двух return

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Calculator.java
> +    public int maxOfTwoNumbers(int x, int y) {
Переименуйте переменные, чтобы проще было читать код

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Task10.java
> +        int x = scanner.nextInt();
Переименовать переменные

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Task5.java
> +        } else if (x < y) {
переменные переименовать нужно

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Task6.java
> +        if (x > y) {
Переименовать переменные

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Task7.java
> +        int x = scanner.nextInt();
Переименовать переменные

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Task8.java
> +        int x = scanner.nextInt();
Переименовать

2022-02-26 12:19 UTC, AlexJavaGuru commented on src/student_nadezda_travkina/lesson4/Task9.java
> +        int x = scanner.nextInt();
Переменные нужно переименовать правильно, чтобы понятно читалось

2022-02-27 12:59 UTC, Nadeezzda commented on src/student_nadezda_travkina/lesson4/Calculator.java
> +    public boolean isEven(int result) {
по какому принципу можно сократить?

2022-02-27 13:06 UTC, Nadeezzda commented on src/student_nadezda_travkina/lesson4/Task10.java
> +        int x = scanner.nextInt();
По какому принципу переименовать?  Вместо Х и У  -  num1/num2? Ведь это калькулятор, переменные не несут никакой смысловой нагрузки, поэтому я не совсем понимаю как их сделать "логичными"...

2022-03-05 07:49 UTC, AlexJavaGuru commented
Жду исправлений

2022-03-10 18:34 UTC, AlexJavaGuru approved these changes
num1, num2 все еще не самые лучшие переменные. Но мучить вас уже не буду

2022-03-10 18:34 UTC, merged