Cosmo
AlexJavaGuru/java_1_wednesday_2022 pull request #8
Opened 2022-01-28 13:10 UTC by SergejGSP

2022-02-01 11:59 UTC, SergejGSP commented
Proba

2022-02-03 19:19 UTC, AlexJavaGuru commented on src/student_sergejgsp/HelloWorld.java
> +import static java.lang.System.*;
Статический импорт штука не очень полезная. Когда классы большие, может быть не понятно откуда вы вызываете те или иные методы заимпорченых статически классов

2022-02-03 19:25 UTC, AlexJavaGuru commented on src/student_sergejgsp/task_11/CalculateFourNumbers.java
> +        int x = 72;
Плохо названы переменные.

2022-02-03 19:27 UTC, AlexJavaGuru requested changes
Посмотрите все файлы, что вы переименовали в папке teacher и верните все, как было

2022-02-03 19:27 UTC, AlexJavaGuru commented on src/student_sergejgsp/task_11/ThreeN.java
> +public class ThreeN<z, y, x> {
Убрать параметризацию класса. Исправить названия переменных.

2022-02-04 21:04 UTC, AlexJavaGuru approved these changes

2022-02-04 21:04 UTC, AlexJavaGuru commented on src/student_sergejgsp/task_11/ThreeN.java
> +public class ThreeN<z, y, x> {
Все еще есть параметризация

2022-02-04 21:04 UTC, merged