J.Soldatova Lesson07
AlexJavaGuru/java_1_wednesday_2022 pull request #84
Opened 2022-03-09 21:04 UTC by NightCatX

lesson07: 
word service
power calculator
caesar cipher

2022-03-21 19:56 UTC, AlexJavaGuru requested changes

2022-03-21 19:56 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_7/level_5_middle/PowerCalculator.java
> +    static int[] getNumbers() {
Этот метод тут лишний. Наш PowerCalculator должен работать с подаваемыми параметрами. А не заниматься запросом этих параметров.

2022-03-21 19:56 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_7/level_5_middle/PowerCalculator.java
> +    static int exponentiationPositive(int[] numbers) {
Поменяйте входной параметр на два отдельных параметра. Не нужно подавать массив.

2022-03-27 17:18 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_7/level_5_middle/PowerCalculator.java
> +    static int[] getNumbers() {
changed

2022-03-27 17:18 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_7/level_5_middle/PowerCalculator.java
> +    static int exponentiationPositive(int[] numbers) {
changed

2022-03-29 12:14 UTC, AlexJavaGuru approved these changes

2022-03-29 12:14 UTC, merged