Igors lessons 3
AlexJavaGuru/java_1_wednesday_2022 pull request #86
Opened 2022-03-11 08:55 UTC by Trigs70

2022-03-21 20:11 UTC, AlexJavaGuru requested changes

2022-03-21 20:11 UTC, AlexJavaGuru commented on src/student_igors/lesson_3/level_7/ProductDemo.java
> +        double regularPrice = 1.2;
Зачем вы эти состояния тут объявили? Они же не нужны. У вас есть объект продукт. У него уже всё есть. Я совсем не понимаю, что вы делаете в demo тут

2022-03-22 10:19 UTC, Trigs70 commented on src/student_igors/lesson_3/level_7/ProductDemo.java
> +        double regularPrice = 1.2;
Добрый день. Тогда мне надо переделать эту работу и опять сделать комит или переделать здесь в GIT?

2022-03-22 20:37 UTC, Trigs70 commented on src/student_igors/lesson_3/level_7/ProductDemo.java
> +        double regularPrice = 1.2;
Добрый вечер Алексей.
Вроде исправил в GITe

2022-03-29 12:13 UTC, AlexJavaGuru approved these changes

2022-03-29 12:13 UTC, merged