J.Soldatova: Lesson09
AlexJavaGuru/java_1_wednesday_2022 pull request #96
Opened 2022-03-27 16:59 UTC by NightCatX

2022-04-02 17:48 UTC, AlexJavaGuru requested changes

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void addNewAtIndex(Object object, int index, List list); //adds new object to the list at specific index
List наверное лишнее состояние. Вы уже создадите ваш лист, он уже будет хранить состояние.

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void removeIndex(int index, List list); //removes object at index from the list
То же самое

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void removeInstance(Object object, List list); //removes specific object from the list
И тут

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void sort(List list); //sorts the list in alphabetic/descending order
И тута

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void sortReverse(List list); //sorts the list in reverse alphabetic/ascending order
Ну вы поняли

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void printList(List list); //prints the list
Да

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_5_middle/Book.java
> +    boolean isRead = false;
false это и так дефолтное состояние для булеана

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_5_middle/BookReaderImpl.java
> +    public String[] returnCurrentBooks() {
Вроде возвращаем киниги...а вернулись строки. Понимаете, к чему я?

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_5_middle/BookReaderImpl.java
> +    public String[] returnReadBooks() {
И тут не киниги вернулись...

2022-04-02 17:48 UTC, AlexJavaGuru commented on src/student_jekaterina_soldatova/lesson_09/level_5_middle/BookReaderImpl.java
> +    public String[] returnNotReadBooks() {
И тут

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void addNewAtIndex(Object object, int index, List list); //adds new object to the list at specific index
done

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void removeIndex(int index, List list); //removes object at index from the list
done

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void removeInstance(Object object, List list); //removes specific object from the list
done

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void sort(List list); //sorts the list in alphabetic/descending order
done

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void sortReverse(List list); //sorts the list in reverse alphabetic/ascending order
done

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_1_intern/MyList.java
> +    void printList(List list); //prints the list
done

2022-04-24 14:30 UTC, NightCatX commented on src/student_jekaterina_soldatova/lesson_09/level_5_middle/Book.java
> +    boolean isRead = false;
done

2022-05-17 17:19 UTC, AlexJavaGuru approved these changes

2022-05-17 17:19 UTC, merged