AJ Lesson 9
AlexJavaGuru/java_1_wednesday_2022 pull request #97
Opened 2022-03-28 00:21 UTC by JaKo2577

Level 1 - 5

2022-04-02 19:05 UTC, AlexJavaGuru requested changes

2022-04-02 19:05 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_9/level_5/BookReaderImpl.java
> +        if (book.getBookName().equals("") || book.getAuthor().equals("")) {
Рекомендую вот эти два условия вынести в отдельный метод - isBookValid(Book book). Пусть он делает то же самое, что и в этой строчке

2022-04-02 19:05 UTC, AlexJavaGuru commented on src/student_aleksandrs_jakovenko/lesson_9/level_5/BookReaderImpl.java
> +        } else if (library.contains(book)) {
А вот это условие, можно объединить с первым, потому, что они они оба возвращают false в случае успеха. Значит можно объединить через AND

2022-04-03 18:36 UTC, JaKo2577 commented on src/student_aleksandrs_jakovenko/lesson_9/level_5/BookReaderImpl.java
> +        } else if (library.contains(book)) {
Попробовал через И - не проходит тесты, через ИЛИ - всё ок

2022-04-16 20:52 UTC, AlexJavaGuru approved these changes

2022-04-16 20:52 UTC, merged